# Generated by Django 3.2.8 on 2022-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name_af',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ar_dz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_be',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_bs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_dsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en_au',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en_gb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_eo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_es_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_es_co',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_es_mx',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_es_ni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_es_ve',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_eu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_fy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ga',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_gd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_gl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_he',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_hr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_hsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ig',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_io',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_is',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_kab',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_km',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_lb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_lv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_mk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ml',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_mn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_mr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_my',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_nb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_nn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_os',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_pa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_pt_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_sk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_sl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_sr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_sr_latn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_te',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_tg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_tk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_tt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_udm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_vi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_zh_hant',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_af',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ar_dz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ast',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_be',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_bg',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_bn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_br',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_bs',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ca',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_cs',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_cy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_da',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_dsb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_el',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_en_au',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_en_gb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_eo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_es_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_es_co',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_es_mx',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_es_ni',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_es_ve',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_et',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_eu',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_fa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_fi',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_fy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ga',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_gd',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_gl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_he',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_hi',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_hr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_hsb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_hu',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_hy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ia',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ig',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ind',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_io',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_is',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_it',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ja',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ka',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_kab',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_kk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_km',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_kn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ko',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ky',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_lb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_lt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_lv',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_mk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ml',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_mn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_mr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_my',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_nb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ne',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_nl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_nn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_os',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_pa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_pl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_pt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_pt_br',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ro',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_sk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_sl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_sq',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_sr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_sr_latn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_sv',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_sw',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ta',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_te',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_tg',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_th',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_tk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_tr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_tt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_udm',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_uk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_ur',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_uz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_vi',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_zh_hans',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_zh_hant',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_af',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ar_dz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_be',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_bs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_dsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_en_au',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_en_gb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_eo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_es_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_es_co',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_es_mx',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_es_ni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_es_ve',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_eu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_fy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ga',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_gd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_gl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_he',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_hr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_hsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ig',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_io',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_is',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_kab',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_km',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_lb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_lv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_mk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ml',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_mn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_mr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_my',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_nb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_nn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_os',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_pa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_pt_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_sk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_sl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_sr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_sr_latn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_te',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_tg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_tk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_tt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_udm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_vi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_zh_hant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
